name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Actualizar repositorio del VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_SSH_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/Frontend
            git pull origin main

      - name: Eliminar contenedor antiguo
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_SSH_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/Frontend
            docker rm -f frontend-web || true

      - name: Construir y ejecutar contenedor
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_SSH_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/Backend
            docker compose up --build -d frontend-web
